export const Heroes = [
  {
    id: '_h1',
    name: 'viking',
    health: 70,
    combatEfficiency: 10,
    magicKnowledge: 10,
    img: '/assets/heroes/viking.png',
  },
  {
    id: '_h2',
    name: 'wizard',
    health: 30,
    combatEfficiency: 2,
    magicKnowledge: 18,
    img: '/assets/heroes/wizard.png',
  },
  {
    id: '_h3',
    name: 'rogue',
    health: 50,
    combatEfficiency: 14,
    magicKnowledge: 4,
    img: '/assets/heroes/rogue.png',
  },
  {
    id: '_h4',
    name: 'knight',
    health: 60,
    combatEfficiency: 13,
    magicKnowledge: 8,
    img: '/assets/heroes/knight.png',
  },
  {
    id: '_h5',
    name: 'archer',
    health: 40,
    combatEfficiency: 16,
    magicKnowledge: 3,
    img: '/assets/heroes/archer.png',
  },
  {
    id: '_h6',
    name: 'druid',
    health: 55,
    combatEfficiency: 10,
    magicKnowledge: 8,
    img: '/assets/heroes/druid.png',
  },
];

export const Monsters = [
  {
    id: '_m1',
    name: 'gnome',
    level: 1,
    health: 15,
    combatEfficiency: 10,
    magicKnowledge: 2,
    img: '/assets/monsters/gnome.png',
  },
  {
    id: '_m2',
    name: 'goblin',
    level: 1,
    health: 18,
    combatEfficiency: 4,
    magicKnowledge: 4,
    img: '/assets/monsters/goblin.png',
  },
  {
    id: '_m3',
    name: 'imp',
    level: 1,
    health: 10,
    combatEfficiency: 7,
    magicKnowledge: 1,
    img: '/assets/monsters/imp.png',
  },
  {
    id: '_m4',
    name: 'ogre',
    level: 2,
    health: 30,
    combatEfficiency: 3,
    magicKnowledge: 2,
    img: '/assets/monsters/ogre.png',
  },
  {
    id: '_m5',
    name: 'troll',
    level: 2,
    health: 35,
    combatEfficiency: 13,
    magicKnowledge: 11,
    img: '/assets/monsters/troll.png',
  },
  {
    id: '_m6',
    name: 'dragon',
    level: 2,
    health: 50,
    combatEfficiency: 15,
    magicKnowledge: 15,
    img: '/assets/monsters/dragon.png',
  },
  {
    id: '_m7',
    name: 'giant',
    level: 3,
    health: 40,
    combatEfficiency: 30,
    magicKnowledge: 1,
    img: '/assets/monsters/giant.png',
  },
  {
    id: '_m8',
    name: 'reaper',
    level: 3,
    health: 22,
    combatEfficiency: 8,
    magicKnowledge: 25,
    img: '/assets/monsters/reaper.png',
  },
  {
    id: '_m9',
    name: 'harpy',
    level: 3,
    health: 36,
    combatEfficiency: 12,
    magicKnowledge: 12,
    img: '/assets/monsters/harpy.png',
  },
  {
    id: '_m10',
    name: 'vampire',
    level: 4,
    health: 66,
    combatEfficiency: 9,
    magicKnowledge: 11,
    img: '/assets/monsters/vampire.png',
  },
];
